### ISSUE TITLE
Hotkey doesn't work.

### ISSUE THREAD

**Issue by madprops** [attilathedud/RedditRandomizer#1]
I tried making different combinations of hotkeys work in the extension settings and nothing worked on Reddit or 4chan, I tried refreshing the pages too. This is on Chrome 60. I tried the default combination which seems to be shift + right. And other custom ones like ctrl + enter and ctrl + space.

**Comment by attilathedud** [comment]
Thank you for the heads up. I was able to reproduce the issue and will fix it once I am back from travelling.

**Comment by attilathedud** [comment]
What OS were you using when this occurred?

**Comment by madprops** [comment]
Windows 10. Btw, Chrome has a built-in shortcut system for extensions. Just saying in case you didn't know. Which might be better than implementing one yourself

**Comment by attilathedud** [comment]
Fixed it as far as I can tell on both Win 7 and Linux Mint. It will be merged into the Chrome Web Store in a few days. Thanks again for your help.
